services:
    iedtools.app:
        class: IlluminateEd\IEdTools\Console\Application
#        arguments: 
#            { name: 'Illuminate Education Tools', version: "%app_version%" }
        calls:
            - [add, ['@ib.command.pgcmin']]

    ib.command.pgcmin:
        class: IlluminateEd\IEdTools\Command\IB\PgcMinCommand
        tags:
        - { name: console.command }
        - { name: console.ib.command }

