imports:
    - { resource: services/commands.yml }

services:
    iedtools.app:
        class: IlluminateEd\IEdTools\Console\Application
        arguments: [ "%app_version%" ]
        calls:
            - [add, ['@command.self_update']]
            - [add, ['@command.ib.pgcmin']]
