imports:
    - { resource: services/commands.yml }

services:
    app.console.toolrepo:
        class: SpacedGAP\ToolRepo\Console\Application
        arguments: [ "%app_version%" ]
        calls:
            - [add, ['@command.self_update']]
            - [add, ['@command.ib.pgcmin']]
    app.console.toolrepo.input:
        class: \Symfony\Component\Console\Input\ArgvInput
    app.console.toolrepo.output:
        class: \Symfony\Component\Console\Output\ConsoleOutput
