imports:
    - { resource: services/commands.yml }

services:
    app.console.toolrepo:
        class: SpacedGAP\ToolRepo\Console\Application
        arguments: [ "%app_version%" ]
        calls:
            - [add, ['@command.self_update']]
            - [add, ['@command.ib.pgcmin']]
